name: Publish packages to GHCR
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
env:
  NODE_VERSIONS: (18, 20)
  JDK_VERSIONS: (8, 11, 17, 21)
  MVN_VERSIONS: ("3.8", "3.9")
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        use-alpine: ["true", "false"]
        mvn-version: ["3.8", "3.9"]
        jdk-version: [8, 11, 17, 21]
        node-version: [18, 20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/docker-publish-action
        with:
          tag_latest: ${{ endsWith(join(env.MVN_VERSIONS), matrix.mvn-version) && endsWith(join(env.JDK_VERSIONS), matrix.jdk-version) && endsWith(join(env.NODE_VERSIONS), matrix.node-version) && 'true' || 'false' }}
          use_alpine: ${{ matrix.use-alpine == 'true' && 'true' || 'false' }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image_name: ${{ github.repository }}
          mvn_version: ${{ matrix.mvn-version }}
          jdk_version: ${{ matrix.jdk-version }}
          node_version: ${{ matrix.node-version }}
