name: Publish packages to GHCR
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  MVN_VERSION: '3.8'
  JDK_VERSION: '18'
  NODE_VERSION: '18.15.0'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:mvn${{ env.MVN_VERSION }}-jdk${{ env.JDK_VERSION }}-n${{ env.NODE_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            MVN_VERSION=${{ env.MVN_VERSION }}
            JDK_VERSION=${{ env.JDK_VERSION }}
            NODE_VERSION=${{ env.NODE_VERSION }}
